# Generated by Django 4.0.5 on 2022-07-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodimageurl',
            name='url',
        ),
        migrations.AddField(
            model_name='foodimageurl',
            name='images_url',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
